apiVersion: v1
kind: Service
metadata:
  name: homework4-postgres-service
  namespace: homework4
  labels:
    app: homework4-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: homework4-db