apiVersion: v1
kind: Secret
metadata:
  name: homework4-secrets
  namespace: homework4
  labels:
    app: homework4-app 
type: Opaque
data:
  DB_USER: ZGV2 
  DB_PASSWORD: ZGV2
  DB_CONNECTION_STRING: U2VydmVyPWhvbWV3b3JrNC1wb3N0Z3Jlcy1zZXJ2aWNlO0RhdGFiYXNlPXVzZXJzO1VzZXIgSWQ9ZGV2O1Bhc3N3b3JkPWRldg==