apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homework4-monitor
  labels:
    app: homework4-app
    
spec:
  endpoints:
    - port: homework4-port
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      scheme: http
#  jobLabel: stack
  namespaceSelector:
    matchNames:
      - homework4
  selector:
    matchLabels:
      app: homework4-app
  
