apiVersion: v1
kind: Service
metadata:
  name: homework-kuber-service
spec:
  selector:
    app: homework-kuber
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
