{
 "title": "Homework4",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency 50 Q",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, method) (rate(nginx_ingress_controller_response_duration_seconds_bucket{status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 95 Q",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method) (rate(nginx_ingress_controller_response_duration_seconds_bucket{status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 99 Q",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, method) (rate(nginx_ingress_controller_response_duration_seconds_bucket{status=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_request_duration_seconds_sum{status=\"200\"}[2m])) / sum by (method)(rate(nginx_ingress_controller_request_duration_seconds_count{status=\"200\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=\"200\"}[2m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_response_duration_seconds_count{status=~\"404|500\"}[2m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Latency 50 Q",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, endpoint, method) (rate(http_request_duration_seconds_bucket{endpoint=~\"api/.*\", code=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 95 Q",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint, method) (rate(http_request_duration_seconds_bucket{endpoint=~\"api/.*\", code=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 99 Q",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, endpoint, method) (rate(http_request_duration_seconds_bucket{endpoint=~\"api/.*\", code=\"200\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (endpoint, method) (rate(http_request_duration_seconds_sum{code=\"200\"}[2m])) / sum by (endpoint, method)(rate(http_request_duration_seconds_count{code=\"200\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{endpoint=~\"api/.*\", code=\"200\"}[2m])) by (endpoint, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"404|500\"}[2m])) by (endpoint, method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}